# Com DuckDB

In [9]:
import duckdb

## Broze

### Despesa

In [18]:
PARQUET_FILE_NAME = "despesa.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,DS_GASTO,DT_PAGAMENTO,VR_GASTO,VR_PAGAMENTO,VR_DOCUMENTO,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:26:12,2025,#NULO#,1,Distrital,DF,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
1,25/04/2026,16:26:12,2025,#NULO#,1,Distrital,DF,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
2,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,CE,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
3,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,MS,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
4,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,SP,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1

In [17]:
PARQUET_FILE_NAME = "classificacao_despesa.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,DESPESA,CLASSIFICACAO
0,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO
1,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,ADMINISTRATIVO
2,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,ADMINISTRATIVO
3,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,ADMINISTRATIVO
4,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,FINALÍSTICO
...,...,...
155,SEGURANCA E VIGILANCIA - DESPESAS ELEITORAIS ...,FINALÍSTICO
156,"DESPESAS COM PRODUCAO DE JINGLES, VINHETAS E S...",FINALÍSTICO
157,AGUA E ESGOTO - MULHERES ...,FINALÍSTICO
158,SEGURANCA E VIGILANCIA - MULHERES ...,FINALÍSTICO
159,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO

## Receita

In [19]:
PARQUET_FILE_NAME = "receita.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,SG_PARTIDO,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,DT_RECEITA,DS_RECEITA,VR_RECEITA
0,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1475,#NULO#,05/08/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,2500
1,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1490,#NULO#,28/08/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,5000
2,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1506,#NULO#,01/10/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,2000
3,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1535,#NULO#,22/12/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,4000
4,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,#NULO#,#NULO#,25/04/2025,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,"1692,07"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194839,25/04/2026,16:27:11,4,Municipal,TO,9683,FÁTIMA,#NULO#,54775347000135,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194840,25/04/2026,16:27:11,4,Municipal,TO,9311,COLINAS DO TOCANTINS,#NULO#,53837785000118,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194841,25/04/2026,16:27:11,4,Municipal,TO,349,JUARINA,#NULO#,54427078000116,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194842,25/04/2026,16:27:11,4,Municipal,TO,9695,BERNARDO SAYÃO,#NULO#,54721419000161,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194843,25/04/2026,16:27:11,4,Municipal,TO,9483,NAZARÉ,#NULO#,55995337000178,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0

## SILVER

### Receita

In [7]:
PARQUET_FILE_NAME = "receita_enriquecida.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,5000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264991,2026-04-25,16:27:11,4,MUNICIPAL,TO,9695,BERNARDO SAYAO,NaN,54721419000161,UNIAO,...,NaN,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264992,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,NaN,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264993,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,NaN,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264994,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,NaN,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264995,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,NaN,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0