# Com DuckDB

In [1]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/despesa.parquet'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
1,25/04/2026,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
2,25/04/2026,16:26:12,2025,None,2,ESTADUAL,CE,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
3,25/04/2026,16:26:12,2025,None,2,ESTADUAL,MS,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
4,25/04/2026,16:26:12,2025,None,2,ESTADUAL,SP,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1

In [ ]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        sg_partido,
        SUM(vl_receita) AS vl_total
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 20
    """
).df()

df.head()

     sg_partido      vl_total
0            PL  2.960729e+08
1            PT  2.317026e+08
2           PSD  1.312535e+08
3  REPUBLICANOS  1.274974e+08
4           MDB  1.237678e+08

In [12]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,sg_partido,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,dt_receita,ds_receita,vl_receita
0,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,None,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00
1,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,None,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00
2,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,None,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00
3,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,None,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00
4,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,None,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07