# Com DuckDB

In [ ]:
import duckdb

In [3]:
PARQUET_FILE_NAME = "cnpj.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    LIMIT 20
    """
).df()

df.head()

,cd_cnpj,nm_empresarial,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,87537000130,COMERCIAL MALLET LTDA,NaN,1994-06-13 00:00:00,SC,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,46,"COMERCIO POR ATACADO, EXCETO VEICULOS AUTOMOTO...",COMERCIO ATACADISTA DE PRODUTOS DE CONSUMO NAO...,46.4,46.42-7,COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E ...,46.42-7/01,COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E ...,2026-04-13 05:46:14.493801000
1,124153000140,EMBALAGENS T 2 LTDA,NaN,1994-07-27 00:00:00,GO,CENTRO-OESTE,MATRIZ,2005-01-08 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,"COMERCIO VAREJISTA DE ARTIGOS CULTURAIS, RECRE...",47.6,47.61-0,"COMERCIO VAREJISTA DE LIVROS, JORNAIS, REVISTA...",47.61-0/03,COMERCIO VAREJISTA DE ARTIGOS DE PAPELARIA,2026-04-13 05:46:14.493801000
2,165731000197,FACILITY TOUR AGENCIA DE TURISMO LTDA,FACILITY TOUR,1994-08-16 00:00:00,SP,SUDESTE,MATRIZ,2004-04-24 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000
3,370353000183,PARANOA HOTEIS E TURISMO LTDA,NaN,1974-01-14 00:00:00,DF,CENTRO-OESTE,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ALOJAMENTO E ALIMENTACAO,55,ALOJAMENTO,HOTEIS E SIMILARES,55.1,55.10-8,HOTEIS E SIMILARES,55.10-8/01,HOTEIS,2026-04-13 05:46:14.493801000
4,373580000162,CYPRESS TURISMO LTDA,CYPRESS TURISMO,1994-12-30 00:00:00,RS,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000

## SILVER

### Receita

In [9]:
PARQUET_FILE_NAME = "receita_enriquecida.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,vl_receita,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,2500.0,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,2500.0,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,2500.0,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,2500.0,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,5000.0,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,5000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264991,2026-04-25,16:27:11,4,MUNICIPAL,TO,9695,BERNARDO SAYAO,NaN,54721419000161,UNIAO,...,0.0,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264992,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,0.0,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264993,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,0.0,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264994,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,0.0,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0
264995,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,0.0,NaN,False,OUTROS,False,False,False,0.0,0.0,0.0