# Com DuckDB

In [2]:
import duckdb

## Broze

### Receita

### Despesa

In [23]:
PARQUET_FILE_NAME = "despesa.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,DS_GASTO,DT_PAGAMENTO,VR_GASTO,VR_PAGAMENTO,VR_DOCUMENTO,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:26:12,2025,#NULO#,1,Distrital,DF,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
1,25/04/2026,16:26:12,2025,#NULO#,1,Distrital,DF,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
2,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,CE,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
3,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,MS,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
4,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,SP,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1

In [24]:
PARQUET_FILE_NAME = "classificacao_despesa.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,DESPESA,CLASSIFICACAO
0,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO
1,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,ADMINISTRATIVO
2,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,ADMINISTRATIVO
3,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,ADMINISTRATIVO
4,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,FINALÍSTICO
...,...,...
155,SEGURANCA E VIGILANCIA - DESPESAS ELEITORAIS ...,FINALÍSTICO
156,"DESPESAS COM PRODUCAO DE JINGLES, VINHETAS E S...",FINALÍSTICO
157,AGUA E ESGOTO - MULHERES ...,FINALÍSTICO
158,SEGURANCA E VIGILANCIA - MULHERES ...,FINALÍSTICO
159,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO

In [20]:
PARQUET_FILE_NAME = "receita.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,SG_PARTIDO,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,DT_RECEITA,DS_RECEITA,VR_RECEITA
0,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1475,#NULO#,05/08/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,2500
1,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1490,#NULO#,28/08/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,5000
2,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1506,#NULO#,01/10/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,2000
3,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1535,#NULO#,22/12/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,4000
4,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,#NULO#,#NULO#,25/04/2025,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,"1692,07"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194839,25/04/2026,16:27:11,4,Municipal,TO,9683,FÁTIMA,#NULO#,54775347000135,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194840,25/04/2026,16:27:11,4,Municipal,TO,9311,COLINAS DO TOCANTINS,#NULO#,53837785000118,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194841,25/04/2026,16:27:11,4,Municipal,TO,349,JUARINA,#NULO#,54427078000116,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194842,25/04/2026,16:27:11,4,Municipal,TO,9695,BERNARDO SAYÃO,#NULO#,54721419000161,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194843,25/04/2026,16:27:11,4,Municipal,TO,9483,NAZARÉ,#NULO#,55995337000178,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0

## SILVER

### Receita

In [21]:
PARQUET_FILE_NAME = "receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,cd_tp_natureza_recurso,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio
0,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,NaN,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00,2025.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,NaN,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00,2025.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,NaN,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00,2025.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,NaN,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00,2025.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,NaN,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194839,2026-04-25,16:27:11,4,MUNICIPAL,TO,9683,FATIMA,NaN,54775347000135,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194840,2026-04-25,16:27:11,4,MUNICIPAL,TO,9311,COLINAS DO TOCANTINS,NaN,53837785000118,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194841,2026-04-25,16:27:11,4,MUNICIPAL,TO,349,JUARINA,NaN,54427078000116,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194842,2026-04-25,16:27:11,4,MUNICIPAL,TO,9695,BERNARDO SAYAO,NaN,54721419000161,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194843,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN

### Despesa

In [25]:
PARQUET_FILE_NAME = "despesa.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,NaN,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
1,2026-04-25,16:26:12,2025,NaN,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
2,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,CE,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
3,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,MS,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
4,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,SP,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196028,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-10-31,0.0,806.61,4598.72,1,FUNDO PARTIDARIO,4052151
196029,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,00360305000104,CAIXA ECONOMICA FEDERAL - CEF,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-02-28,0.0,25.05,455.91,1,FUNDO PARTIDARIO,4050872
196030,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-04-30,0.0,107.70,1960.92,1,FUNDO PARTIDARIO,4051614
196031,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-09-30,0.0,455.45,3297.81,1,FUNDO PARTIDARIO,4052150
196032,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-05-31,0.0,5.12,1609.03,1,FUNDO PARTIDARIO,4051786

In [26]:
PARQUET_FILE_NAME = "classificacao_despesa.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

                                            nm_despesa        tp_gasto
0    DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...  ADMINISTRATIVO
1    TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
2    TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...  ADMINISTRATIVO
3    TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
4    TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...     FINALÍSTICO
..                                                 ...             ...
155  SEGURANCA E VIGILANCIA - DESPESAS ELEITORAIS  ...     FINALÍSTICO
156  DESPESAS COM PRODUCAO DE JINGLES, VINHETAS E S...     FINALÍSTICO
157  AGUA E ESGOTO - MULHERES                      ...     FINALÍSTICO
158  SEGURANCA E VIGILANCIA - MULHERES             ...     FINALÍSTICO
159  DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...  ADMINISTRATIVO

[160 rows x 2 columns]

## GOLD

In [4]:
PARQUET_FILE_NAME = "partido_ano_receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/04-gold/{PARQUET_FILE_NAME}'
    )
    """
).df()

df.head()

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AGIR,2025.0,1207854.99,0.00,716425.63,467986.60,56,0.000000,59.313878,2.156884e+04
1,AGIR,NaN,0.00,0.00,0.00,0.00,0,NaN,NaN,NaN
2,AVANTE,2025.0,53620628.37,29443076.52,260244.61,11696480.12,41,54.909980,0.485344,1.307820e+06
3,AVANTE,NaN,0.00,0.00,0.00,0.00,0,NaN,NaN,NaN
4,CIDADANIA,2025.0,11751454.30,3815505.23,501646.01,7429741.60,79,32.468366,4.268799,1.487526e+05